### ISSUE TITLE
CSV example is dangerous and misleading

### ISSUE THREAD

**Issue by Tux** [balajirama/Text-Parser#1]
One cannot state that a "simple" CSV parser will just work using `split`. It might on very simple data, but this is bound to break.
Please rewrite your example to using the de-facto CSV parsers that CPAN already offers: Text::CSV_XS and it's slower relative Text::CSV. Even *if* you'd use the suggested change below, embedded newlines will break your code. Your example will - of course - already break on fields having a `,` in it
```
diff -purd a/lib/Text/Parser.pm b/lib/Text/Parser.pm
--- a/lib/Text/Parser.pm        2019-01-02 05:30:41.000000000 +0100
+++ b/lib/Text/Parser.pm        2019-01-02 11:58:36.616080248 +0100
@@ -420,12 +420,14 @@ We will write a parser for a simple CSV

     package Text::Parser::CSV;
     use parent 'Text::Parser';
+    use Text::CSV_XS;

+    my $csv;
     sub save_record {
         my ($self, $line) = @_;
-        chomp $line;
-        my (@fields) = split /,/, $line;
-        $self->SUPER::save_record(\@fields);
+        $csv //= Text::CSV_XS->new ({ binary => 1, auto_diag => 1});
+        $csv->parse ($line);
+        $self->SUPER::save_record([$csv->fields]);
     }

 That's it! Now in C<main::> you can write something like this:
@@ -441,6 +443,8 @@ That's it! Now in C<main::> you can writ

 The above program reads the content of a given CSV file and prints the content out in space-separated form.

+Note that this approach does B<NOT> handle embedded newlines!
+
 =head2 Example 2 : Error checking

 It is easy to add any error checks using exceptions. One of the easiest ways to do this is to C<use L<Exception::Class>>. We'll modify the CSV parser above to demonstrate that.
```
And using that in the test-files (PASS)
```
diff -purd a/t/Text-Parser-pod-02.t b/t/Text-Parser-pod-02.t
--- a/t/Text-Parser-pod-02.t    2019-01-02 05:30:41.000000000 +0100
+++ b/t/Text-Parser-pod-02.t    2019-01-02 12:08:41.254027777 +0100
@@ -3,11 +3,13 @@ use warnings;

 package Text::Parser::CSV;
 use parent 'Text::Parser';
+use Text::CSV_XS;
+
+my $csv = Text::CSV_XS->new ({ binary => 1, auto_diag => 1 });

 sub save_record {
     my ( $self, $line ) = @_;
-    chomp $line;
-    my (@fields) = split /,/, $line;
+    my @fields = $csv->parse ($line) ? $csv-> fields : ();
     $self->SUPER::save_record( \@fields );
 }

diff -purd a/t/Text-Parser-pod-03.t b/t/Text-Parser-pod-03.t
--- a/t/Text-Parser-pod-03.t    2019-01-02 05:30:41.000000000 +0100
+++ b/t/Text-Parser-pod-03.t    2019-01-02 12:07:49.221516851 +0100
@@ -6,11 +6,13 @@ use parent 'Text::Parser';
 use Exception::Class ( 'Text::Parser::CSV::Error',
     'Text::Parser::CSV::TooManyFields' =>
         { isa => 'Text::Parser::CSV::Error', }, );
+use Text::CSV_XS;
+
+my $csv = Text::CSV_XS->new ({ binary => 1, auto_diag => 1 });

 sub save_record {
     my ( $self, $line ) = @_;
-    chomp $line;
-    my (@fields) = split /,/, $line;
+    my @fields = $csv->parse ($line) ? $csv-> fields : ();
     $self->{__csv_header} = \@fields if not scalar( $self->get_records );
     Text::Parser::CSV::TooManyFields->throw(
         error => "Too many fields on line #" . $self->lines_parsed )
```

**Comment by balajirama** [comment]
Hi @Tux,

Thanks for your feedback. Yes, I could do that, but I just wanted to show the ease of writing a parser. The code you suggested is surely better. Would you mind sending me a pull request after editing with the latest version I published last night? That way, your change will reflect on the git commits and my Diet::Zilla builder should automatically pick that up and give you credit on the next release.

Thanks,
Balaji

**Comment by Tux** [comment]
I could, but I didn't do that, as it adds a dependency to your test-environment.
And then you should choose on which parser you want to depend: Text::CSV or Text::CSV_XS

**Comment by balajirama** [comment]
For now let's alter just the POD. The test can be updated based on what
your recommendation is.

I think Text::CSV might be better to depend on because I don't want my test
dependencies to prevent people from trying out the module. But I'm open to
your thoughts on this.

Thanks,
Balaji

**Comment by balajirama** [comment]
Thanks @Tux for your contribution. I've merged the changes. But I also request that you edit Example 2 since that is also just an extension of Example 1 and is just an "error checking" CSV parser. Since you know better about the CSV, maybe you know a few other error conditions that should be caught. I suggest all those additions. And yes, I would request your test script too. Once again, don't edit the existing tests, just add a new one.

**Comment by Tux** [comment]
Some comments:
[DZ] beginning to build Text-Parser
[Git::NextVersion] Bumping version from 0.752 to 0.753
[DZ] guessing dist's main_module is lib/Text/Parser.pm
Pod::Weaver::Section::Contributors (for section Contributors) does not appear to be installed

PR on its way

**Comment by balajirama** [comment]
Code changes have been pulled I will include it in the next release tonight.
